@startuml

skinparam {

    shadowing false
    arrowColor #46749F

    RectangleBorderColor #CCCCCC
    RectangleBackgroundColor #F5F2F0

    ComponentBorderColor #46749F
    ComponentBackgroundColor #E5ECF0

    UsecaseBorderColor #46749F
    UsecaseBackgroundColor #E5ECF0

    ControlBorderColor #0081C6
    ControlBackgroundColor #55DDCA

    frameBorderColor #0081C6
    packageBorderColor #0081C6

    noteBorderColor #468847
    noteBackgroundColor #DFF0D8
}


control "<size:20>Dart Target</size> \n <size:20>Platforms</size>" as source


rectangle "Web" as web {

    usecase dart2js [
        dart2js
        dartdevc
    ]

    [Angular Dart] as angular [[https://webdev.dartlang.org/angular]]
    note right of angular
        Components, Directives, Templates...
        similar to TypeScript version,
        but with Dart language power & beauty
    end note
    angular ---> dart2js

    [OverReact] as overReact [[https://pub.dartlang.org/packages/over_react]]
    note right of overReact: Statically typed \nReact
    overReact --> dart2js

    [dart:html] as dartHtml [[https://webdev.dartlang.org/guides/web-programming#low-level-html]]
    note top of dartHtml
        Low level HTML
        DOM modification
        jquery like
    end note
    dartHtml -> dart2js

    [Stage XL] as stageXL [[http://www.stagexl.org/]]
    note bottom of stageXL
        2D Web games
        Adobe Flash like APIs
    end note
    stageXL -> dart2js

    frame Browser #E5ECF0 {
        artifact JavaScript
        artifact EcmaScript6
    }

    dart2js --> JavaScript: production \n JS
    dart2js --> EcmaScript6: human \n readable \n JS
}

rectangle "Mobile" as mobile #FFFDCC {
    [Flutter] as flutter [[https://flutter.io]]
    note right of flutter
        Productive (hot reload)
        Fast & Native (no webview)
        React-like APIs
    end note

    frame iOS #E5ECF0 {
        artifact IPA
    }

    frame Android #E5ECF0 {
        artifact APK
    }

    flutter --> IPA: AOT compile to native code
    flutter --> APK
}

rectangle "Fuchsia OS" as fuchsia #FDEFE7 {
    [Fuchsia UI] as fuchsiaUI [[https://fuchsia.googlesource.com/docs/+/master/book.md]]

    [Flutter] as fuchsiaFlutter

    package "Dart VM" as fuchsiaVM #E5ECF0 {
        artifact fuchsiaApp [
            Fuchsia App
        ]
    }

    fuchsiaUI -> fuchsiaFlutter
    fuchsiaFlutter -> fuchsiaApp

}

rectangle "Server" as server {
    [Aqueduct \n Angel \nRedstone] as aqueduct [[https://aqueduct.io/]]

    [dart:io \n dart:path \n dart:args] as cmdlinePackages [[https://www.dartlang.org/tutorials/dart-vm/cmdline]]

    package "Dart VM" #E5ECF0 {
        artifact cmdline [
            cmdline utils
            scripts
        ]
        database "Server App" as enterprise
    }

    aqueduct -> enterprise: REST \n ORM \n PostgreSQL \nMongoDB
    cmdlinePackages -> cmdline
}


source -up-|> mobile
source -up-|> web
source -down-|> fuchsia
source -down-|> server

@enduml