@startuml

skinparam {

    shadowing false
    arrowColor #46749F

    RectangleBorderColor #CCCCCC
    RectangleBackgroundColor #F5F2F0

    ComponentBorderColor #46749F
    ComponentBackgroundColor #E5ECF0

    UsecaseBorderColor #46749F
    UsecaseBackgroundColor #E5ECF0

    ControlBorderColor #0081C6
    ControlBackgroundColor #55DDCA

    frameBorderColor #0081C6
    packageBorderColor #0081C6

    noteBorderColor #468847
    noteBackgroundColor #DFF0D8

    AgentBorderColor #468847
    AgentBackgroundColor #DFF0D8

}


control "<size:20>Dart Target</size> \n <size:20>Platforms</size>" as source


rectangle "Web" as web {

    agent dartdevc [[https://webdev.dartlang.org/tools/dartdevc]]

    agent dart2js [[https://webdev.dartlang.org/tools/dart2js]]

    [Angular Dart \n OverReact \n Stage XL \n dart:html] as angular [[https://webdev.dartlang.org/angular]]
    angular -down-> dart2js: production
    angular -down-> dartdevc: development

    frame Browser #E5ECF0 {
        artifact JavaScript
        artifact EcmaScript6
    }

    dart2js -> JavaScript: fast \n minified\n JS
    dartdevc -> EcmaScript6: human \n readable \n JS
}

rectangle "Mobile" as mobile #FFFDCC {
    [Flutter] as flutter [[https://flutter.io]]

    frame iOS #E5ECF0 {
        artifact IPA
    }

    frame Android #E5ECF0 {
        artifact APK
    }

    flutter --> IPA: AOT compile to native code
    flutter --> APK
}

rectangle "Fuchsia OS" as fuchsia #FDEFE7 {
    [Fuchsia UI] as fuchsiaUI [[https://fuchsia.googlesource.com/docs/+/master/book.md]]

    [Flutter] as fuchsiaFlutter

    package "Dart VM" as fuchsiaVM #E5ECF0 {
        artifact fuchsiaApp [
            Fuchsia App
        ]
    }

    fuchsiaUI -> fuchsiaFlutter
    fuchsiaFlutter -> fuchsiaApp

}

rectangle "Server" as server {
    [Aqueduct \n Angel \nRedstone] as aqueduct [[https://aqueduct.io/]]

    [dart:io \n dart:path \n dart:args] as cmdlinePackages [[https://www.dartlang.org/tutorials/dart-vm/cmdline]]

    package "Dart VM" #E5ECF0 {
        artifact cmdline [
            cmdline utils
            scripts
        ]
        database "Server App" as enterprise
    }

    aqueduct -> enterprise: REST \n ORM \n PostgreSQL \nMongoDB
    cmdlinePackages -> cmdline
}


source -up-|> mobile
source -up-|> web
source -down-|> fuchsia
source -down-|> server

@enduml